/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fUqjbNnJMLM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function AssingQR() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1
              className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              Vincula tu cuenta
            </h1>
            <p
              className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Escanea el código QR para vincular tu cuenta de forma rápida y segura.
            </p>
          </div>
          <div className="w-full max-w-md">
            <img
              alt="Código QR"
              className="mx-auto aspect-square rounded-xl object-contain"
              height="400"
              src="/placeholder.svg"
              width="400" />
          </div>
          <div className="mt-4 space-y-2">
            <p className="text-sm font-medium leading-none">Instrucciones:</p>
            <ol
              className="list-decimal space-y-1 pl-5 text-sm text-gray-500 dark:text-gray-400">
              <li>Abre la aplicación de cámara en tu dispositivo móvil.</li>
              <li>Enfoca el código QR en el área central.</li>
              <li>Sigue las instrucciones en tu dispositivo para completar el proceso.</li>
            </ol>
          </div>
        </div>
      </div>
    </section>)
  );
}
